name: Website Downtime Monitor

on:
  schedule:
    - cron: "*/5 * * * *"  # runs every 5 minutes
  workflow_dispatch:       # lets you run manually from GitHub

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          npm init -y
          npm install -D @playwright/test
          npm install -g browserstack-playwright

      - name: Run Playwright tests on BrowserStack
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          browserstack-playwright --config=playwright.config.ts
